"""Central color palette used across the app.

Define a single source of truth for UI colors so different views stay consistent.
"""

PRIMARY_COLOR = "#28C7D3"
PRIMARY_DARK = "#0A777F"
ACCENT_RED = "#E53935"
BACKGROUND_GRAY = "#F2F2F2"
WHITE = "#FFFFFF"
DARK_GRAY = "#212121"

# Backwards-compatible aliases
SECONDARY_COLOR = "#10B981"
DANGER_COLOR = ACCENT_RED
WARNING_COLOR = "#F59E0B"
BG_COLOR = WHITE
CARD_BG = WHITE
BORDER_COLOR = "#E8EEF5"
TEXT_PRIMARY = DARK_GRAY
TEXT_SECONDARY = "#6B7280"
TEXT_LIGHT = "#9CA3AF"
ACCENT_COLOR = "#8B5CF6"
SHADOW_COLOR = "rgba(0, 0, 0, 0.08)"

__all__ = [
    "PRIMARY_COLOR", "PRIMARY_DARK", "ACCENT_RED", "BACKGROUND_GRAY",
    "WHITE", "DARK_GRAY", "SECONDARY_COLOR", "DANGER_COLOR", "WARNING_COLOR",
    "BG_COLOR", "CARD_BG", "BORDER_COLOR", "TEXT_PRIMARY", "TEXT_SECONDARY",
    "TEXT_LIGHT", "ACCENT_COLOR", "SHADOW_COLOR",
]
